name: flightdata
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=9.8.0.87
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.45.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.9.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyzmq=26.2.1
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.2
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - idna==3.10
      - importlib-resources==6.5.2
      - joblib==1.4.2
      - keras==3.9.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - narwhals==1.29.0
      - numpy==2.0.2
      - nvidia-nccl-cu12==2.25.1
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.14.1
      - pandas==2.2.3
      - pillow==11.1.0
      - plotly==6.0.0
      - protobuf==5.29.3
      - pyparsing==3.2.1
      - pytz==2025.1
      - requests==2.32.3
      - rich==13.9.4
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xgboost==2.1.4
